library(TSA)

#Exhibit 5.1 Monthly Price of Oil: January 1986-January 2006
data(oil.price)
plot(oil.price, ylab='Price per Barrel',type='l')
oil.price

#Exhibit 5.3 An Explosive "AR(1)" Series
data(explode.s)
explode.s
plot(explode.s,ylab=expression(Y[t]),type='o')

#Exhibit 5.4 The Difference Series of the Logs of the Oil Price Time
plot(diff(log(oil.price)),ylab='Change in Log(Price)',type='l')

#Exhibit 5.5 Simulation of an IMA(2,2) Series with ??1 = 1 and ??2 = ???0.6
data(ima22.s)
plot(ima22.s,ylab='IMA(2,2) Simulation',type='o')

#Exhibit 5.6 First Difference of the Simulated IMA(2,2) Series
plot(diff(ima22.s),ylab='First Difference',type='o')

#Exhibit 5.7 Second Difference of the Simulated IMA(2,2) Series
plot(diff(ima22.s,difference=2),ylab='Differenced Twice',type='o')

#Exhibit 5.8 U.S. Electricity Generated by Month
data(electricity); plot(electricity)

#Exhibit 5.9 Time Series Plot of Logarithms of Electricity Values
plot(log(electricity),ylab='Log(electricity)')

#Exhibit 5.10 Difference of Logarithms for Electricity Time Series
plot(diff(log(electricity)), 
     ylab='Difference of Log(electricity)')
#Exhibit 5.11 Log-likelihood versus Lambda
BoxCox.ar(electricity)
